#!/usr/bin/env bash
# Locates a usable Kotlin compiler and prints a command that runs it.
#
# Order of preference:
#   1. $KOTLIN_HOME/bin/kotlinc      (a real Kotlin distribution)
#   2. kotlinc on PATH
#   3. the kotlin-compiler-embeddable jar bundled with a Gradle install
#
# (3) is the interesting one: any machine with Gradle already has a full Kotlin
# compiler on disk, so the project can be compiled and its tests run without
# downloading anything. This is how the port was verified in an offline sandbox.
#
#   eval "$(tools/find-kotlinc.sh)"      # sets KOTLINC and KOTLIN_LIB
set -euo pipefail

emit() {
  printf 'KOTLINC=%q\n' "$1"
  printf 'KOTLIN_LIB=%q\n' "$2"
  printf 'export KOTLINC KOTLIN_LIB\n'
}

if [[ -n "${KOTLIN_HOME:-}" && -x "$KOTLIN_HOME/bin/kotlinc" ]]; then
  emit "$KOTLIN_HOME/bin/kotlinc" "$KOTLIN_HOME/lib"
  exit 0
fi

if command -v kotlinc >/dev/null 2>&1; then
  BIN="$(command -v kotlinc)"
  HOME_DIR="$(cd "$(dirname "$(readlink -f "$BIN")")/.." && pwd)"
  emit "$BIN" "$HOME_DIR/lib"
  exit 0
fi

# --- fall back to the compiler inside a Gradle distribution -------------------
GRADLE_LIB=""
for guess in \
    ${GRADLE_HOME:+"$GRADLE_HOME/lib"} \
    /opt/gradle-*/lib /usr/share/gradle*/lib \
    "$HOME"/.sdkman/candidates/gradle/*/lib \
    "$HOME"/.gradle/wrapper/dists/*/*/gradle-*/lib; do
  if compgen -G "$guess/kotlin-compiler-embeddable-*.jar" >/dev/null 2>&1; then
    GRADLE_LIB="$guess"
    break
  fi
done

if [[ -z "$GRADLE_LIB" ]]; then
  echo "no Kotlin compiler found: install kotlinc, or set KOTLIN_HOME" >&2
  exit 2
fi

# Build a private kotlin-home with the filenames the compiler expects, then a
# tiny launcher script. Both live under tools/.kotlinc so nothing is downloaded.
HERE="$(cd "$(dirname "$0")" && pwd)"
CACHE="$HERE/.kotlinc"
mkdir -p "$CACHE/kotlin-home/lib"
for base in kotlin-stdlib kotlin-reflect kotlin-script-runtime; do
  SRC="$(compgen -G "$GRADLE_LIB/$base-[0-9]*.jar" | sort | tail -1 || true)"
  [[ -n "$SRC" ]] && cp -f "$SRC" "$CACHE/kotlin-home/lib/$base.jar"
done

CP="$(compgen -G "$GRADLE_LIB/kotlin-compiler-embeddable-*.jar" | sort | tail -1)"
for extra in kotlin-stdlib kotlin-reflect kotlin-script-runtime \
             kotlin-daemon-embeddable kotlinx-coroutines-core-jvm \
             trove4j annotations kotlinx-metadata-jvm; do
  MATCH="$(compgen -G "$GRADLE_LIB/$extra-[0-9]*.jar" | sort | tail -1 || true)"
  [[ -n "$MATCH" ]] && CP="$CP:$MATCH"
done

cat > "$CACHE/kotlinc" <<LAUNCHER
#!/usr/bin/env bash
# Generated by tools/find-kotlinc.sh — Kotlin CLI over Gradle's embedded compiler.
exec env JAVA_TOOL_OPTIONS= java -Xmx3g -cp "$CP" \\
  org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \\
  -kotlin-home "$CACHE/kotlin-home" "\$@"
LAUNCHER
chmod +x "$CACHE/kotlinc"

emit "$CACHE/kotlinc" "$CACHE/kotlin-home/lib"
