#!/usr/bin/env python3
"""Generates `com/vepro/code/R.java` from res/values/public.xml.

On a real build aapt2 emits R.java while it compiles the resource table. This
script produces the identical class from the same source of truth (public.xml
pins every id explicitly), so the app can be compiled and type-checked with no
Android SDK present at all.

    python3 tools/gen_r.py [output-dir]        # default: tools/gen
"""
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "res/values/public.xml"
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tools/gen"


def main():
    if not PUBLIC.is_file():
        sys.exit(f"missing {PUBLIC}")
    groups = {}
    for node in ET.parse(PUBLIC).getroot():
        if node.tag != "public":
            continue
        kind = node.attrib["type"]
        groups.setdefault(kind, []).append((node.attrib["name"], node.attrib["id"]))

    lines = [
        "package com.vepro.code;",
        "",
        "/**",
        " * Generated by tools/gen_r.py from res/values/public.xml.",
        " * Mirrors the aapt2-generated R so the app compiles without an SDK.",
        " * DO NOT EDIT - regenerate instead.",
        " */",
        "public final class R {",
        "    private R() { }",
    ]
    for kind in sorted(groups):
        lines.append(f"    public static final class {kind} {{")
        lines.append(f"        private {kind}() {{ }}")
        for name, ident in sorted(groups[kind]):
            lines.append(f"        public static final int {name} = {ident};")
        lines.append("    }")
    lines.append("}")

    target = OUT / "com/vepro/code/R.java"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(len(v) for v in groups.values())
    print(f"wrote {target} ({total} ids across {len(groups)} types)")


if __name__ == "__main__":
    main()
